anhaidgroup/py_stringmatching

py_stringmatching/tests/test_simfunctions.py

Adding none and type tests, all combinations

---

benchmarks/benchamarks.py
docs/Simfunctions.rst
py_stringmatching/simfunctions.py
py_stringmatching/tests/test_simfunctions.py

Add Generalized Jaccard similarity measure

---

benchmarks/benchamarks.py
docs/Simfunctions.rst
py_stringmatching/simfunctions.py
py_stringmatching/tests/test_simfunctions.py
py_stringmatching/utils.py

Adding Editex distance measure

---

benchmarks/benchamarks.py
py_stringmatching/similarity_measure/affine.py
py_stringmatching/similarity_measure/bag_distance.py
py_stringmatching/similarity_measure/cosine.py
py_stringmatching/similarity_measure/dice.py
py_stringmatching/similarity_measure/editex.py
py_stringmatching/similarity_measure/generalized_jaccard.py
py_stringmatching/similarity_measure/hamming_distance.py
py_stringmatching/similarity_measure/hybrid_similarity_measure.py
py_stringmatching/similarity_measure/jaccard.py
py_stringmatching/similarity_measure/jaro.py
py_stringmatching/similarity_measure/jaro_winkler.py
py_stringmatching/similarity_measure/levenshtein.py
py_stringmatching/similarity_measure/monge_elkan.py
py_stringmatching/similarity_measure/needleman_wunsch.py
py_stringmatching/similarity_measure/overlap_coefficient.py
py_stringmatching/similarity_measure/phonetic_similarity_measure.py
py_stringmatching/similarity_measure/sequence_similarity_measure.py
py_stringmatching/similarity_measure/similarity_measure.py
py_stringmatching/similarity_measure/smith_waterman.py
py_stringmatching/similarity_measure/soft_tfidf.py
py_stringmatching/similarity_measure/soundex.py
py_stringmatching/similarity_measure/tfidf.py
py_stringmatching/similarity_measure/token_similarity_measure.py
py_stringmatching/similarity_measure/tversky_index.py
py_stringmatching/tests/test_simfunctions.py

Please review.
@sanjibkd  @kvpradap

Enhan convert sim to class

---

py_stringmatching/tests/test_tokenizers.py
py_stringmatching/tokenizer/alphabetic_tokenizer.py
py_stringmatching/tokenizer/alphanumeric_tokenizer.py
py_stringmatching/tokenizer/definition_tokenizer.py
py_stringmatching/tokenizer/delimiter_tokenizer.py
py_stringmatching/tokenizer/qgram_tokenizer.py
py_stringmatching/tokenizer/tokenizer.py
py_stringmatching/tokenizer/whitespace_tokenizer.py
py_stringmatching/utils.py

Please review.
@sanjibkd  @kvpradap

Enhan convert tok to class

---

py_stringmatching/similarity_measure/affine.py
py_stringmatching/similarity_measure/cython_levenshtein.pyx
py_stringmatching/similarity_measure/hamming_distance.py
py_stringmatching/similarity_measure/jaro.py
py_stringmatching/similarity_measure/jaro_winkler.py
py_stringmatching/similarity_measure/levenshtein.py
py_stringmatching/similarity_measure/needleman_wunsch.py
py_stringmatching/similarity_measure/smith_waterman.py
py_stringmatching/similarity_measure/soft_tfidf.py
py_stringmatching/tests/test_simfunctions.py
py_stringmatching/utils.py

@kvpradap can you take a look ?

Enhan fix non ascii

---

py_stringmatching/similarity_measure/ratio.py
py_stringmatching/similarity_measure/token_sort.py
py_stringmatching/tests/test_simfunctions.py
py_stringmatching/utils.py

Added token sort similarity measure with test cases. Token sort has dependency on ratio similarity measure. Added fuzzy wuzzy ratio similarity measure also in this branch.

Feat fz token sort

---

py_stringmatching/similarity_measure/partial_ratio.py
py_stringmatching/similarity_measure/partial_token_sort.py
py_stringmatching/tests/test_simfunctions.py
py_stringmatching/utils.py

Added fuzzy wuzzy partial token sort ratio similarity measure with test cases. Added partial ratio also in this branch as partial token sort ratio has dependency on partial ratio similarity measure.

Added fuzzy wuzzy partial token sort ratio similarity measure with test cases. 

---

py_stringmatching/similarity_measure/ratio.py
py_stringmatching/tests/test_simfunctions.py

Added fuzzy wuzzy ratio similarity measure with test cases

added fuzzy wuzzy ratio similarity measure with test cases

---

py_stringmatching/similarity_measure/partial_ratio.py
py_stringmatching/tests/test_simfunctions.py

Added fuzzy wuzzy partial ratio similarity measure with test cases

added fuzzy wuzzy partial ratio similarity measure with test cases

---

py_stringmatching/similarity_measure/cython/cython_needleman_wunsch.pyx
py_stringmatching/similarity_measure/needleman_wunsch.py
setup.py

--Added cython code to increase the performance of Needleman-Wunsch measure

Enhan_needleman_wunsch_cython

---

py_stringmatching/similarity_measure/cython/cython_smith_waterman.pyx
py_stringmatching/similarity_measure/smith_waterman.py
setup.py

-- Added cython function to Smith Waterman measure to improve the performance.

Enhan_smith_waterman_cython

---

py_stringmatching/similarity_measure/affine.py
py_stringmatching/similarity_measure/cython/cython_affine.pyx
py_stringmatching/similarity_measure/cython/cython_jaro.pyx
py_stringmatching/similarity_measure/cython/cython_utils.pyx
py_stringmatching/tests/test_simfunctions.py
setup.py

--Added cython functions for Affine measure to improve the performance
--Modified the test cases for Affine measure
--Added functions to find max int and max float in cython_utils.pyx

Enhan affine cython

---

docs/Installation.rst

Added warning to the user that this package requires a C compiler to run. This warning also contains a link to the issues page that gives more detailed information.

Updated installation instructions.

---

.travis.yml
py_stringmatching/similarity_measure/bag_distance.py

Fixed a broken link referencing to the paper for bag distance.

[Doc] Fixed bag distance reference link.

---

appveyor.yml

Updated the appveyor.yml file to include testing for python version 3.7 on windows.

Added testing for python 3.7

---

README.rst
docs/Installation.rst
docs/WhatIsNew.rst
setup.py

Updated Documentation for new release 0.4.1. The new documentations updates the what is new section of the user manual. It also updates the various versions of python now supported for this package.

Doc rel 0.4.1

---

.coveragerc
.gitignore
.travis.yml
appveyor.yml
build_tools/requirements_dev.txt
docs/Contributing.rst
py_stringmatching/tests/test_sim_Soundex.py
py_stringmatching/tests/test_simfunctions.py
py_stringmatching/tests/test_tokenizers.py
py_stringmatching/tests/utils.py

Switch from nose to vanilla unittest (#78)

---

setup.py

Reverts anhaidgroup/py_stringmatching#93

Revert "Replace underscore with hyphen in project name"

---

.github/workflows/testing.yml
README.rst
setup.py

Reverts anhaidgroup/py_stringmatching#94

Revert "Add support for Python 3.12"
